### PR TITLE
fix(ci/freebsd): install ca certs to prevent certificate-related issues

### LINKED ISSUE #4749: CI on FreeBSD is failing due to `SSH peer certificate or SSH remote key`
Looks like an instance of https://github.com/rust-lang/cargo/issues/16357, and thus https://github.com/alexcrichton/curl-rust/issues/632:

```console
+ cargo build --locked --profile release --target x86_64-unknown-freebsd --no-default-features --features curl-backend,reqwest-native-tls --features vendored-openssl --features reqwest-rustls-tls
      Updating crates.io index
  error: failed to get `anstream` as a dependency of package `rustup v1.29.0 (/home/runner/work/rustup/rustup)`
  
  Caused by:
    download of config.json failed
  
  Caused by:
    failed to download from `[https://index.crates.io/config.json`](https://index.crates.io/config.json%60)
  
  Caused by:
    [60] SSL peer certificate or SSH remote key was not OK (SSL certificate OpenSSL verify result: unable to get local issuer certificate (20))
Error: The process '/usr/bin/ssh' failed with exit code 101
```
_https://github.com/rust-lang/rustup/actions/runs/23097325730/job/67091975295_

### LINKED ISSUE #4760: CI on FreeBSD is failing due to regression in `libz-sys`
Observed in https://github.com/rust-lang/rustup/pull/4758#issuecomment-4083805979:

> I think in principle this should work but I have encountered another regression in `libz-sys` (maybe caused by https://github.com/rust-lang/rustup/pull/4753)... so now we have 3 different issues for FreeBSD now!

```smalltalk
cargo:warning=ToolExecError: command did not execute successfully (status code exit status: 1): LC_ALL="C" "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-unknown-freebsd" "-I" "src/zlib" "-w" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/home/runner/work/rustup/rustup/target/x86_64-unknown-freebsd/release/build/libz-sys-046af476f6182d2e/out/lib/f0389296f42960e9-gzread.o" "-c" "src/zlib/gzread.c"cargo:warning=src/zlib/gzwrite.c:82:49: error: use of undeclared identifier 'EWOULDBLOCK'
    cargo:warning=                if (errno == EAGAIN || errno == EWOULDBLOCK)
    cargo:warning=                                                ^
    cargo:warning=src/zlib/gzwrite.c:117:53: error: use of undeclared identifier 'EWOULDBLOCK'
    cargo:warning=                    if (errno == EAGAIN || errno == EWOULDBLOCK)
    cargo:warning=                                                    ^
    cargo:warning=2 errors generated.
  
    exit status: 1
    cargo:warning=ToolExecError: command did not execute successfully (status code exit status: 1): LC_ALL="C" "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-unknown-freebsd" "-I" "src/zlib" "-w" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/home/runner/work/rustup/rustup/target/x86_64-unknown-freebsd/release/build/libz-sys-046af476f6182d2e/out/lib/f0389296f42960e9-gzwrite.o" "-c" "src/zlib/gzwrite.c"
```
_https://github.com/rust-lang/rustup/actions/runs/23254426636/job/67605187428?pr=4758_

### PR DESCRIPTION
**Pull request by rami3l**
Basically we are reproducing https://github.com/rust-lang/rustup/pull/3810 here. Not really sure if this is enough to have FreeBSD CI running again...

Closes #4749, also closes #4760, both without touching the gist.

OTOH this won't be closing https://github.com/rust-lang/rustup/issues/4751 since we are pinning onto the old FreeBSD version now.

### CODE REVIEW

**Comment by rami3l** [comment]
I think in principle this should work but I have encountered another regression in `libz-sys` (maybe caused by https://github.com/rust-lang/rustup/pull/4753)... so now we have 3 different issues for FreeBSD now!

---

Update: Transferred to #4760.

**Comment by rami3l** [comment]
Fix verified in https://github.com/rust-lang/rustup/actions/runs/23288593795/job/67718138780.

cc @djc to see whether the `ca_root_nss` reapplication could be worth investigating (I think that's unlikely our direct responsibility since the immediate problem is on Cargo's side).

File: Cargo.toml [hunk 1]
```diff
@@ -62,6 +62,9 @@ home = "0.5.4"
 indicatif = "0.18"
 itertools = "0.14"
 libc = "0.2"
+# HACK: Temporarily pinned due to `zlib` regression, to be removed when
+# <https://github.com/madler/zlib/issues/1168> lands.
+libz-sys = "=1.1.24"
```
Comment (ChrisDenton) [inline Cargo.toml]: Would it be worth only pinning this only for FreeBSD?

Comment (rami3l) [reply Cargo.toml]: @ChrisDenton Interesting observation! I'll try that :)

Comment (rami3l) [reply Cargo.toml]: @ChrisDenton Verified again in https://github.com/rust-lang/rustup/actions/runs/23291142015/job/67726791428.

**Review by ChrisDenton — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustup/4758/4b2c0919cfd11db5f79695509a71b217a88bac68..0875b0f63b8c98223196b09e086f221ed22a7db6)*

**Comment by djc** [comment]
> cc @djc to see whether the `ca_root_nss` reapplication could be worth investigating (I think that's unlikely our direct responsibility since the immediate problem is on Cargo's side).

Sounds like the fix is to get Cargo off of curl/OpenSSL...

**Comment by rami3l** [comment]
BTW the CI did pass on trunk again which is good news (for now)...
