### ISSUE TITLE
CI on FreeBSD is failing due to regression in `libz-sys`

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#4760]
Observed in https://github.com/rust-lang/rustup/pull/4758#issuecomment-4083805979:

> I think in principle this should work but I have encountered another regression in `libz-sys` (maybe caused by https://github.com/rust-lang/rustup/pull/4753)... so now we have 3 different issues for FreeBSD now!

```smalltalk
cargo:warning=ToolExecError: command did not execute successfully (status code exit status: 1): LC_ALL="C" "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-unknown-freebsd" "-I" "src/zlib" "-w" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/home/runner/work/rustup/rustup/target/x86_64-unknown-freebsd/release/build/libz-sys-046af476f6182d2e/out/lib/f0389296f42960e9-gzread.o" "-c" "src/zlib/gzread.c"cargo:warning=src/zlib/gzwrite.c:82:49: error: use of undeclared identifier 'EWOULDBLOCK'
    cargo:warning=                if (errno == EAGAIN || errno == EWOULDBLOCK)
    cargo:warning=                                                ^
    cargo:warning=src/zlib/gzwrite.c:117:53: error: use of undeclared identifier 'EWOULDBLOCK'
    cargo:warning=                    if (errno == EAGAIN || errno == EWOULDBLOCK)
    cargo:warning=                                                    ^
    cargo:warning=2 errors generated.
  
    exit status: 1
    cargo:warning=ToolExecError: command did not execute successfully (status code exit status: 1): LC_ALL="C" "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-unknown-freebsd" "-I" "src/zlib" "-w" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/home/runner/work/rustup/rustup/target/x86_64-unknown-freebsd/release/build/libz-sys-046af476f6182d2e/out/lib/f0389296f42960e9-gzwrite.o" "-c" "src/zlib/gzwrite.c"
```
_https://github.com/rust-lang/rustup/actions/runs/23254426636/job/67605187428?pr=4758_

**Comment by ChrisDenton** [comment]
https://github.com/madler/zlib/issues/1168

**Comment by rami3l** [comment]
@ChrisDenton I'm closing this for now but I'm open to reopening it if this turns out to be more than FreeBSD :)

**Comment by djc** [comment]
Obviously the fix for this is to rip out curl, which would avoid the dependency on libz-sys.

**Comment by rami3l** [comment]
> Obviously the fix for this is to rip out curl, which would avoid the dependency on libz-sys.

@djc I have had my patch since years ago! Shall I rebase it now (rolling up my sleeves)?

**Comment by djc** [comment]
Sounds good to me!
